export function enableCollapsibleBlocks(): void {
  // Select all possible header classes generated by the renderer
  const headers = document.querySelectorAll(
    ".role-message-header, " +
    ".loop-block-outside-role-header, .loop-block-inside-role-header, " + 
    ".switch-block-outside-role-header, .switch-block-inside-role-header, " +
    ".conditional-section-header"
  );

  headers.forEach((header) => {
    const container = header.parentElement;
    if (!container) return;

    // Add a class to show it's clickable (pointer cursor)
    header.classList.add("collapsible-header");

    // Clean up old listeners to prevent "double-toggling" on re-renders
    const newHeader = header.cloneNode(true) as HTMLElement;
    header.parentNode?.replaceChild(newHeader, header);

    newHeader.addEventListener("click", () => {
      container.classList.toggle("collapsed");
    });
  });
}